"""Projects tab API (issue #1199, epic #1192): charter parsing, overview assembly, routes.

The GitHub fetch is monkeypatched at ``projects.service.gh_api``; the staff run
store is a temp SQLite file so the steward-run join is exercised for real.
"""

from __future__ import annotations

import base64
import json
import os
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
from fastapi import HTTPException
from fastapi.testclient import TestClient

_BACKEND = Path(__file__).resolve().parents[2] / "backend"
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))
os.environ.setdefault("DASHBOARD_API_KEY", "test-key")

from projects import charter, service  # noqa: E402
from staff import store as store_mod  # noqa: E402

CHARTER = """# Project Charter

## End Goal

Ship the thing.

## Non-Goals

- Boiling the ocean.

## Features

| ID  | Feature | Status      | Tracking | Notes |
| --- | ------- | ----------- | -------- | ----- |
| F1  | Parser  | shipped     | #1       | done  |
| F2  | Router  | in-progress | #1199    |       |
| F3  | Page    | planned     | -        |       |
| F4  | Bots    | parked      | #4       |       |
"""

STATUS = """<!-- generated by project-steward; do not hand-edit -->

# Project Status

## Progress

| ID | Feature | Status | Progress | Last change |
| --- | --- | --- | --- | --- |
| F1 | Parser | shipped | 100% | 2026-09-22 |

## Blockers

- None recorded.

## Decisions Needed

- Adopt the charter contract fleet-wide?
- Park F4 permanently.
"""


def _contents(text: str) -> dict[str, Any]:
    return {"content": base64.b64encode(text.encode("utf-8")).decode("ascii"), "encoding": "base64"}


def _run(run_id: str, role: str, repo: str, **fields: Any) -> store_mod.RunRecord:
    base: dict[str, Any] = {
        "provider": "claude",
        "model": None,
        "machine": "m",
        "target_kind": "prompt",
        "target_ref": "",
        "prompt": "p",
    }
    return store_mod.RunRecord(id=run_id, role=role, repo=repo, **{**base, **fields})


def _fake_gh(files: dict[str, str]) -> Any:
    """A ``gh_api`` stand-in serving ``{"<repo>/<path>": text}``; anything else is a 404."""

    async def fake(endpoint: str) -> dict[str, Any]:
        for key, text in files.items():
            repo, path = key.split("/", 1)
            if endpoint == f"/repos/{service.ORG}/{repo}/contents/{path}":
                return _contents(text)
        raise HTTPException(status_code=404, detail=f"GitHub resource not found: {endpoint}")

    return fake


@pytest.fixture
def projects_env(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Iterator[Path]:
    monkeypatch.setenv("STAFF_RUNS_DB", str(tmp_path / "runs.sqlite3"))
    config = tmp_path / "projects.json"
    config.write_text(json.dumps({"repos": ["Alpha", "Beta"]}), encoding="utf-8")
    monkeypatch.setattr(service, "_CONFIG_PATH", config)
    store_mod.reset_store()
    yield config
    store_mod.reset_store()


@pytest.fixture
def client(projects_env: Path, monkeypatch: pytest.MonkeyPatch) -> TestClient:  # noqa: ARG001
    """Bare app with only the projects router (the staff tests do the same).

    ``HUB_FLEET_TOKEN`` is unset so ``require_fleet_peer`` is a no-op; the
    structural perimeter is covered by ``test_structural_auth_perimeter.py``.
    """
    from fastapi import FastAPI
    from routers import projects as projects_router

    monkeypatch.delenv("HUB_FLEET_TOKEN", raising=False)
    app = FastAPI()
    app.include_router(projects_router.router)
    return TestClient(app, raise_server_exceptions=False)


# ── Contract pins ─────────────────────────────────────────────────────────────


def test_charter_contract_pinned() -> None:
    """Mirrors Repository_Management shared_scripts/project_charter.py; change both or neither."""
    assert charter.FEATURE_COLUMNS == ("ID", "Feature", "Status", "Tracking", "Notes")
    assert charter.VALID_STATUSES == frozenset({"planned", "in-progress", "shipped", "parked"})
    assert charter.REQUIRED_SECTIONS == ("End goal", "Non-goals", "Features")
    assert charter.STATUS_HEADER == "<!-- generated by project-steward; do not hand-edit -->"


def test_parse_charter_and_progress() -> None:
    features = charter.parse_charter(CHARTER)
    assert [f.id for f in features] == ["F1", "F2", "F3", "F4"]
    first = {"id": "F1", "feature": "Parser", "status": "shipped", "tracking": "#1", "notes": "done"}
    assert features[0].to_dict() == first
    assert charter.feature_progress(features) == {
        "planned": 1,
        "in_progress": 1,
        "shipped": 1,
        "parked": 1,
        "percent_shipped": 25,
    }


def test_parse_charter_rejects_bad_status_and_columns() -> None:
    with pytest.raises(charter.CharterError, match="invalid status 'done'"):
        charter.parse_charter(CHARTER.replace("| shipped     |", "| done        |"))
    with pytest.raises(charter.CharterError, match="columns"):
        charter.parse_charter(CHARTER.replace("| Tracking |", "| Issue    |"))
    assert charter.validate_charter(CHARTER) == []


def test_parse_decisions_needed() -> None:
    assert charter.parse_decisions_needed(STATUS) == ["Adopt the charter contract fleet-wide?", "Park F4 permanently"]
    assert charter.parse_decisions_needed(STATUS.replace("- Adopt", "- None recorded.\n- Adopt")) == [
        "Adopt the charter contract fleet-wide?",
        "Park F4 permanently",
    ]
    assert charter.parse_decisions_needed("# nothing here") == []


# ── Service ───────────────────────────────────────────────────────────────────


def test_configured_repos_reads_config_and_falls_back(projects_env: Path) -> None:
    assert service.configured_repos() == ["Alpha", "Beta"]
    projects_env.write_text("{not json", encoding="utf-8")
    assert service.configured_repos() == list(service.DEFAULT_REPOS)
    projects_env.write_text(json.dumps({"repos": ["../evil", "ok_repo"]}), encoding="utf-8")
    assert service.configured_repos() == ["ok_repo"]


async def test_build_project_charter_present(projects_env: Path) -> None:  # noqa: ARG001
    fake = _fake_gh({"Alpha/docs/project/CHARTER.md": CHARTER, "Alpha/docs/project/STATUS.md": STATUS})
    result = await service.build_project("Alpha", fetch=fake)
    assert result["charter_present"] is True
    assert result["status_present"] is True
    assert result["progress"]["percent_shipped"] == 25
    assert [f["id"] for f in result["features"]] == ["F1", "F2", "F3", "F4"]
    assert result["decisions_needed"] == ["Adopt the charter contract fleet-wide?", "Park F4 permanently"]
    assert result["last_steward_run"] is None
    assert "error" not in result


async def test_build_project_charter_missing(projects_env: Path) -> None:  # noqa: ARG001
    result = await service.build_project("Alpha", fetch=_fake_gh({}))
    assert result == {
        "repo": "Alpha",
        "charter_present": False,
        "features": [],
        "progress": {"planned": 0, "in_progress": 0, "shipped": 0, "parked": 0, "percent_shipped": 0},
        "status_present": False,
        "decisions_needed": [],
        "last_steward_run": None,
    }


async def test_build_project_charter_malformed_reports_error(projects_env: Path) -> None:  # noqa: ARG001
    bad = CHARTER.replace("| planned     |", "| someday     |")
    result = await service.build_project("Alpha", fetch=_fake_gh({"Alpha/docs/project/CHARTER.md": bad}))
    assert result["charter_present"] is True
    assert result["features"] == []
    assert result["error"].startswith("charter invalid: Feature F3: invalid status 'someday'")


async def test_build_project_github_error_is_reported_not_raised(projects_env: Path) -> None:  # noqa: ARG001
    async def boom(_endpoint: str) -> dict[str, Any]:
        raise HTTPException(status_code=502, detail="GitHub API error: rate limited")

    result = await service.build_project("Alpha", fetch=boom)
    assert result["charter_present"] is False
    assert result["error"] == "github: GitHub API error: rate limited"


def test_last_steward_run_picks_newest_for_repo(projects_env: Path) -> None:  # noqa: ARG001
    store = store_mod.get_store()
    store.create_run(_run("r1", "project-steward", "Alpha", created_at="2026-09-21T00:00:00Z"))
    store.create_run(_run("r2", "project-steward", "Alpha", status="succeeded", created_at="2026-09-22T00:00:00Z"))
    store.create_run(_run("r3", "night-watch", "Alpha", created_at="2026-09-23T00:00:00Z"))
    store.create_run(_run("r4", "project-steward", "Beta", created_at="2026-09-23T00:00:00Z"))
    run = service.last_steward_run("Alpha", store)
    assert run is not None and run["id"] == "r2" and run["status"] == "succeeded"
    assert service.last_steward_run("Gamma", store) is None


# ── Routes ────────────────────────────────────────────────────────────────────


def test_list_projects_route(client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(service, "gh_api", _fake_gh({"Alpha/docs/project/CHARTER.md": CHARTER}))
    resp = client.get("/api/projects")
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["count"] == 2 and [p["repo"] for p in body["projects"]] == ["Alpha", "Beta"]
    alpha, beta = body["projects"]
    assert alpha["charter_present"] is True and alpha["progress"]["shipped"] == 1
    assert beta["charter_present"] is False and "error" not in beta
    assert body["cache_ttl_seconds"] == 600.0


def test_get_project_route_and_unknown_repo(client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(service, "gh_api", _fake_gh({"Beta/docs/project/STATUS.md": STATUS}))
    resp = client.get("/api/projects/Beta")
    assert resp.status_code == 200, resp.text
    assert resp.json()["decisions_needed"] == ["Adopt the charter contract fleet-wide?", "Park F4 permanently"]
    assert client.get("/api/projects/NotConfigured").status_code == 404


def test_overview_is_cached_but_steward_run_is_live(client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    calls: list[str] = []
    inner = _fake_gh({"Alpha/docs/project/CHARTER.md": CHARTER})

    async def counting(endpoint: str) -> dict[str, Any]:
        calls.append(endpoint)
        return await inner(endpoint)

    monkeypatch.setattr(service, "gh_api", counting)
    assert client.get("/api/projects/Alpha").json()["last_steward_run"] is None
    first_calls = len(calls)
    assert first_calls == 2  # charter + status
    store_mod.get_store().create_run(_run("r9", "project-steward", "Alpha"))
    again = client.get("/api/projects/Alpha").json()
    assert again["last_steward_run"]["id"] == "r9"
    assert again["charter_present"] is True
    assert len(calls) == first_calls  # served from cache
