"""Parser for ``docs/project/CHARTER.md`` and ``docs/project/STATUS.md`` (issue #1199).

MIRRORED CONTRACT. This is a deliberate copy of Repository_Management
``shared_scripts/project_charter.py`` (PR #1679): the dashboard never imports from
Repository_Management (CLAUDE.md cross-repo rule), so the small parser is duplicated
here and ``tests/api/test_projects_router.py::test_charter_contract_pinned`` pins the
column names and status vocabulary so drift between the two copies is caught.

Contract:

- ``## End Goal`` and ``## Non-Goals`` come first, in that order (case-insensitive).
- ``## Features`` holds one markdown table with the columns
  ``| ID | Feature | Status | Tracking | Notes |``.
- ``Status`` is one of ``planned``, ``in-progress``, ``shipped``, ``parked``.
- ``Tracking`` is ``#123``, ``owner/repo#123`` or ``-``.
- STATUS.md starts with ``<!-- generated by project-steward; do not hand-edit -->`` and
  has a ``## Decisions Needed`` section whose bullets are the open decisions.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Sequence
from dataclasses import asdict, dataclass
from typing import Any

FEATURE_COLUMNS: tuple[str, ...] = ("ID", "Feature", "Status", "Tracking", "Notes")
VALID_STATUSES: frozenset[str] = frozenset({"planned", "in-progress", "shipped", "parked"})
REQUIRED_SECTIONS: tuple[str, ...] = ("End goal", "Non-goals", "Features")
STATUS_HEADER = "<!-- generated by project-steward; do not hand-edit -->"
DECISIONS_SECTION = "decisions needed"
NONE_RECORDED = "none recorded"

_HEADING = re.compile(r"^##\s+(?P<title>.+?)\s*$")
_TRACKING = re.compile(r"^(?:-|(?:[\w.-]+/[\w.-]+)?#\d+)$")
_BULLET = re.compile(r"^\s*[-*]\s+(?P<text>.+?)\s*$")


class CharterError(ValueError):
    """Raised when a charter violates the contract."""


@dataclass(frozen=True)
class Feature:
    """One row of the charter's Features table."""

    id: str
    feature: str
    status: str
    tracking: str
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _split_row(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def _is_separator(cells: Sequence[str]) -> bool:
    return bool(cells) and all(re.fullmatch(r":?-{3,}:?", c) for c in cells)


def sections(text: str) -> dict[str, list[str]]:
    """Return ``{lower-cased heading: lines}`` for every ``##`` heading, in order.

    HTML comment blocks are skipped so the template's contract comment cannot
    introduce a heading.
    """
    result: dict[str, list[str]] = {}
    current: str | None = None
    in_comment = False
    for line in text.splitlines():
        stripped = line.strip()
        if in_comment:
            if "-->" in stripped:
                in_comment = False
            continue
        if stripped.startswith("<!--") and "-->" not in stripped:
            in_comment = True
            continue
        match = _HEADING.match(line)
        if match:
            current = match.group("title").strip().lower()
            result.setdefault(current, [])
            continue
        if current is not None:
            result[current].append(line)
    return result


def _feature_table(lines: Iterable[str]) -> list[Feature]:
    rows = [ln for ln in lines if ln.strip().startswith("|")]
    if not rows:
        raise CharterError("Features section has no markdown table")
    header = _split_row(rows[0])
    if tuple(header) != FEATURE_COLUMNS:
        expected = " | ".join(FEATURE_COLUMNS)
        raise CharterError(f"Features table columns must be | {expected} |, got | {' | '.join(header)} |")
    features: list[Feature] = []
    seen: set[str] = set()
    for raw in rows[1:]:
        cells = _split_row(raw)
        if _is_separator(cells):
            continue
        if len(cells) != len(FEATURE_COLUMNS):
            raise CharterError(f"Feature row has {len(cells)} cells: {raw.strip()}")
        feature_id, name, status, tracking, notes = cells
        if not feature_id:
            raise CharterError(f"Feature row has an empty ID: {raw.strip()}")
        if feature_id in seen:
            raise CharterError(f"Duplicate feature ID {feature_id!r}")
        seen.add(feature_id)
        if status not in VALID_STATUSES:
            allowed = ", ".join(sorted(VALID_STATUSES))
            raise CharterError(f"Feature {feature_id}: invalid status {status!r} (allowed: {allowed})")
        if not _TRACKING.match(tracking):
            raise CharterError(f"Feature {feature_id}: tracking must be '#N', 'owner/repo#N' or '-', got {tracking!r}")
        features.append(Feature(feature_id, name, status, tracking, notes))
    return features


def parse_charter(text: str) -> list[Feature]:
    """Parse the Features table of a charter; raise ``CharterError`` if invalid."""
    found = sections(text)
    missing = [s for s in REQUIRED_SECTIONS if s.lower() not in found]
    if missing:
        raise CharterError(f"Charter is missing sections: {', '.join(missing)}")
    order = [s.lower() for s in REQUIRED_SECTIONS[:2]]
    heads = list(found)
    if heads[:2] != order:
        raise CharterError(f"Charter must open with '## End Goal' then '## Non-Goals'; found {heads[:2]}")
    return _feature_table(found["features"])


def feature_progress(features: Sequence[Feature]) -> dict[str, int]:
    """Count features per status and the integer percent shipped."""
    counts = {"planned": 0, "in_progress": 0, "shipped": 0, "parked": 0}
    for feature in features:
        counts[feature.status.replace("-", "_")] += 1
    total = len(features)
    percent = round(100 * counts["shipped"] / total) if total else 0
    return {**counts, "percent_shipped": percent}


def validate_charter(text: str) -> list[str]:
    """Return a list of contract violations (empty when the charter is valid)."""
    try:
        parse_charter(text)
    except CharterError as exc:
        return [str(exc)]
    return []


def parse_decisions_needed(status_text: str) -> list[str]:
    """Return the bullets under STATUS.md's ``## Decisions Needed`` section.

    The template placeholder ``None recorded.`` is not a decision. A STATUS.md
    without the generated header is still read: the steward may be mid-migration.
    """
    lines = sections(status_text).get(DECISIONS_SECTION, [])
    decisions: list[str] = []
    for line in lines:
        match = _BULLET.match(line)
        if not match:
            continue
        text = match.group("text").rstrip(".").strip()
        if text.lower() != NONE_RECORDED:
            decisions.append(text)
    return decisions
